In [1]:
# Import some useful libraries
%matplotlib inline
import pandas as pd
import urllib
import xml.etree.ElementTree as ET
from scraper import *
import numpy as np
import scipy.sparse as sp
from tables import *
import json
%load_ext autoreload
%autoreload 2

# display all pandas columns

pd.set_option('display.max_columns', 100)

In [2]:
active = pd.read_csv('data/ActivePeople.csv')

In [3]:
tables = Tables()
interest = tables.active_interest(cosign=True, auth=True)
interest.to_csv('data/ActiveInterests.csv', encoding='utf-8', index=False)
interest.head()

/home/gael/anaconda3/lib/python3.5/site-packages/IPython/core/interactiveshell.py:2821: DtypeWarning: Columns (10,27) have mixed types. Specify dtype option on import or set low_memory=False.
  if self.run_code(code, result):

TagName,Politique d‘Etat,Politique internationale,Politique de sécurité,Politique européenne,Droit,Économie,Finances,Questions sociales,Éducation,Médias et communication,Science et recherche,Emploi et travail,Transports,Environnement,Agriculture,Énergie,Parlement,Droit civil,Droit pénal,Justice,Droit international,Droits de l'homme,Fiscalité,Politique migratoire,Culture,Protection sociale,Santé,Aménagement du territoire et logement,Inconnu,PersonIdCode
0,6,2,3,3,3,7,3,7,7,4,2,1,12,4,2,6,1,3,1,0,0,2,5,1,3,1,1,1,275,2287.0
1,110,57,96,40,86,136,109,74,27,70,11,14,299,89,104,33,27,9,11,2,2,8,18,54,27,10,101,32,274,2292.0
2,43,25,62,12,41,37,44,32,22,18,6,0,69,35,70,14,11,0,0,0,0,0,0,29,7,0,31,17,365,2310.0
3,60,49,33,22,75,153,74,116,38,24,10,7,58,29,9,31,12,0,1,0,0,2,1,33,13,6,77,14,542,2143.0
4,73,49,36,26,47,65,96,45,16,33,9,7,80,38,23,29,24,8,10,1,4,5,12,34,18,6,45,17,236,2147.0

In [3]:
tables = Tables()
interest = tables.active_interest(cosign=True, auth=False)
interest.to_csv('data/ActiveCosign.csv', encoding='utf-8', index=False)
interest.head()

/home/gael/anaconda3/lib/python3.5/site-packages/IPython/core/interactiveshell.py:2821: DtypeWarning: Columns (10,27) have mixed types. Specify dtype option on import or set low_memory=False.
  if self.run_code(code, result):

TagName,Politique d‘Etat,Politique internationale,Politique de sécurité,Politique européenne,Droit,Économie,Finances,Questions sociales,Éducation,Médias et communication,Science et recherche,Emploi et travail,Transports,Environnement,Agriculture,Énergie,Parlement,Droit civil,Droit pénal,Justice,Droit international,Droits de l'homme,Fiscalité,Politique migratoire,Culture,Protection sociale,Santé,Aménagement du territoire et logement,Inconnu,PersonIdCode
0,5,2,3,3,3,7,3,7,5,4,1,1,11,2,2,6,1,3,1,0,0,2,5,1,3,1,1,1,240,2287.0
1,107,57,95,38,84,130,105,71,27,58,10,13,245,79,102,31,26,9,10,2,2,8,14,52,27,9,94,31,262,2292.0
2,43,24,62,12,41,37,44,32,22,18,6,0,69,35,70,14,11,0,0,0,0,0,0,29,7,0,31,17,364,2310.0
3,51,46,30,22,67,132,63,102,35,23,10,6,52,29,9,29,12,0,1,0,0,2,1,29,13,6,71,14,487,2143.0
4,46,30,28,20,42,59,68,23,15,17,7,5,61,31,22,20,19,8,6,0,2,3,9,29,13,5,39,16,187,2147.0

In [10]:
cols = np.array(interest.columns)[:-1]

In [11]:
len(cols)

29

In [12]:
themes = {}
for i in range(len(cols)):
    json = {}
    json['val'] = i
    themes[cols[i]] = json

In [13]:
themes['Agriculture']['english'] = "Agriculture"
themes['Culture']['english'] = "Culture"
themes['Droit']['english'] = "Law"
themes['Droit civil']['english'] = "Civil Law"
themes['Droit international']['english'] = "International Law"
themes['Droit pénal']['english'] = "Penal Law"
themes["Droits de l'homme"]['english'] = "Human Rights"
themes['Emploi et travail']['english'] = "Employment"
themes['Environnement']['english'] = "Environment"
themes['Finances']['english'] = "Finances"
themes['Fiscalité']['english'] = "Taxation"
themes['Justice']['english'] = "Justice"
themes['Médias et communication']['english'] = "Medias"
themes['Parlement']['english'] = "Parliament"
themes['Politique de sécurité']['english'] = "Safety Policy"
themes['Politique d‘Etat']['english'] = "State Policy"
themes['Politique européenne']['english'] = "European Policy"
themes['Politique internationale']['english'] = "International Policy"
themes['Politique migratoire']['english'] = "Migration Policy"
themes['Protection sociale']['english'] = "Social Security"
themes['Questions sociales']['english'] = "Social Questions"
themes['Santé']['english'] = "Health"
themes['Science et recherche']['english'] = "Science"
themes['Transports']['english'] = "Transport"
themes['Économie']['english'] = "Economy"
themes['Éducation']['english'] = "Education"
themes['Énergie']['english'] = "Energy"
themes['Inconnu']['english'] = "Unknown"
themes['Aménagement du territoire et logement']['english'] = "Lands and Housing"

In [14]:
themes

{'Agriculture': {'english': 'Agriculture', 'val': 14},
 'Aménagement du territoire et logement': {'english': 'Lands and Housing',
  'val': 27},
 'Culture': {'english': 'Culture', 'val': 24},
 'Droit': {'english': 'Law', 'val': 4},
 'Droit civil': {'english': 'Civil Law', 'val': 17},
 'Droit international': {'english': 'International Law', 'val': 20},
 'Droit pénal': {'english': 'Penal Law', 'val': 18},
 "Droits de l'homme": {'english': 'Human Rights', 'val': 21},
 'Emploi et travail': {'english': 'Employment', 'val': 11},
 'Environnement': {'english': 'Environment', 'val': 13},
 'Finances': {'english': 'Finances', 'val': 6},
 'Fiscalité': {'english': 'Taxation', 'val': 22},
 'Inconnu': {'english': 'Unknown', 'val': 28},
 'Justice': {'english': 'Justice', 'val': 19},
 'Médias et communication': {'english': 'Medias', 'val': 9},
 'Parlement': {'english': 'Parliament', 'val': 16},
 'Politique de sécurité': {'english': 'Safety Policy', 'val': 2},
 'Politique d‘Etat': {'english': 'State Policy', 'val': 0},
 'Politique européenne': {'english': 'European Policy', 'val': 3},
 'Politique internationale': {'english': 'International Policy', 'val': 1},
 'Politique migratoire': {'english': 'Migration Policy', 'val': 23},
 'Protection sociale': {'english': 'Social Security', 'val': 25},
 'Questions sociales': {'english': 'Social Questions', 'val': 7},
 'Santé': {'english': 'Health', 'val': 26},
 'Science et recherche': {'english': 'Science', 'val': 10},
 'Transports': {'english': 'Transport', 'val': 12},
 'Économie': {'english': 'Economy', 'val': 5},
 'Éducation': {'english': 'Education', 'val': 8},
 'Énergie': {'english': 'Energy', 'val': 15}}

In [4]:
import json
with open('data/themes.json', "w") as outfile:
    json.dump(themes, outfile)

NameError: name 'themes' is not defined

In [15]:
import json
def prepare_d3(in_1, out_):
    interest = pd.read_csv(in_)
    interest.head()
    cols = np.array(interest.columns)[:-1]
    interest_json = {}
    for i in range(len(interest)):
        id_ = int(interest.PersonIdCode[i])
        array = []
        for i in themes.keys():
            val_json = {}
            val_json["int"] = int(interest[interest.PersonIdCode == id_][i])
            val_json["theme"] = themes[i]["english"]
            val_json["idx"] = themes[i]["val"]
            array.append(val_json)
        interest_json[str(id_)] = array
    with open(out_, "w") as outfile:
        json.dump(interest_json, outfile)   
        
def prepare_hist(in_1, in_2, out_):
    interest1 = pd.read_csv(in_1)
    interest2 = pd.read_csv(in_2)
    cols = np.array(interest.columns)[:-1]
    interest_json = {}
    for i in range(len(interest1)):
        id_ = int(interest1.PersonIdCode[i])
        array = []
        for i in themes.keys():
            val_json = {}
            val_json["auth"] = int(interest1[interest1.PersonIdCode == id_][i])
            val_json["cos"] = int(interest2[interest2.PersonIdCode == id_][i])
            val_json["theme"] = themes[i]["english"]
            val_json["idx"] = themes[i]["val"]
            array.append(val_json)
        interest_json[str(id_)] = array
    with open(out_, "w") as outfile:
        json.dump(interest_json, outfile)

In [18]:
prepare_d3('data/ActiveAuthors.csv', '../viz/data/authors.json')
prepare_d3('data/ActiveInterests.csv', '../viz/data/interests.json')

In [16]:
prepare_hist('data/ActiveAuthors.csv', 'data/ActiveCosign.csv', '../viz/data/auth_cos.json')

In [12]:
interest_json = {}
for i in range(len(interest)):
    id_ = int(interest.PersonIdCode[i])
    array = []
    for i in themes.keys():
        val_json = {}
        val_json["int"] = int(interest[interest.PersonIdCode == id_][i])
        val_json["theme"] = themes[i]["english"]
        val_json["idx"] = themes[i]["val"]
        array.append(val_json)
    interest_json[str(id_)] = array

In [13]:
import json
with open('../viz/data/authors.json', "w") as outfile:
    json.dump(interest_json, outfile)

In [214]:
df_business = pd.read_csv('data/Business.csv')
df_role = pd.read_csv('data/BusinessRole.csv')
temp = pd.read_csv('data/Tags.csv')
active = pd.read_csv('data/ActivePeople.csv')

/home/gael/anaconda3/lib/python3.5/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (10,27) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [215]:
# get tag for each business
df_business_tags = df_business[['ID', 'Tags']].set_index('ID')
df_business_tags = df_business_tags.dropna(axis=0)

In [216]:
# create a DataFrame business->tag filled with zero
topics = pd.DataFrame(index=df_business_tags.index)
for i in temp.ID:
    topics[i] = 0

# split the tag "4|8|12" in a list(4, 8, 12)
df_business_tags['Tags'] = df_business_tags['Tags'].apply(lambda x: x.split('|'))

# fill the cell of topics table
def fill_cell(business_number, tags_array):
    for tag in tags_array:
        previous_val = topics.get_value(int(business_number), int(tag))
        topics.set_value(int(business_number), int(tag), int(previous_val + 1))

for i, tags in zip(df_business_tags.index, df_business_tags.Tags):
    fill_cell(i, tags)

# ensure topics has type integer
topics = topics.astype(int)

In [217]:
topics.head()

,4,8,9,10,12,15,24,28,32,34,36,44,48,52,55,66,421,1211,1216,1221,1231,1236,2446,2811,2831,2836,2841,2846
ID,,,,,,,,,,,,,,,,,,,,,,,,,,,,
19910311,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
19950076,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
19970419,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
19980038,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
19982017,1,1,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [121]:
persons = df_role.loc[(df_role.MemberCouncilNumber.notnull())]
auth_cos = persons.loc[(persons.RoleName == 'Auteur') | (persons.RoleName == 'Cosignataire')]
authors = persons.loc[(persons.RoleName == 'Auteur')]
cosign = persons.loc[(persons.RoleName == 'Cosignataire')]

In [143]:
auth_cos = auth_cos[['MemberCouncilNumber', 'BusinessNumber']]
auth_cos = auth_cos[auth_cos.MemberCouncilNumber.isin(active.PersonNumber)]
auth_cos = auth_cos.astype(int)

In [126]:
authors = authors[['MemberCouncilNumber', 'BusinessNumber']]
authors = authors[authors.MemberCouncilNumber.isin(active.PersonNumber)]
authors = authors.astype(int)

In [128]:
cosign = cosign[['MemberCouncilNumber', 'BusinessNumber']]
cosign = cosign[cosign.MemberCouncilNumber.isin(active.PersonNumber)]
cosign = cosign.astype(int)

In [131]:
active.PersonNumber[0]

74

In [147]:
interest = authors.join(topics, on='BusinessNumber', how='inner')

In [156]:
len(persons.loc[(persons.RoleName == 'Auteur')])

31095

In [153]:
len(topics)

30612

In [150]:
tt = authors[authors.MemberCouncilNumber == 74]
tt

        MemberCouncilNumber  BusinessNumber
1478                     74        19933666
1482                     74        19933504
9861                     74        19943223
12942                    74        19943102
16511                    74        19953399
26762                    74        19963658
27793                    74        19961115
27972                    74        19963120
28641                    74        19963082
29735                    74        19963352
29789                    74        19960471
35759                    74        19963343
37702                    74        19973341
38285                    74        19973109
42052                    74        19970424
42928                    74        19973477
43901                    74        19973634
46686                    74        19973474
48678                    74        19973475
49825                    74        19983060
51350                    74        19983324
54173                    74        19983477
55175                    74        19983581
57196                    74        19983325
59958                    74        19983556
60453                    74        19983518
64330                    74        19993372
65894                    74        19993138
67095                    74        19993134
70766                    74        19993541
72129                    74        19993542
74841                    74        20003103
78285                    74        20003699
78648                    74        20003554
80338                    74        20003727
80490                    74        20003705
85083                    74        20003250
86534                    74        20000426
91771                    74        20013140
350739                   74        20160462

In [151]:
for i in tt.BusinessNumber:
    print(cosign[cosign.BusinessNumber == i].MemberCouncilNumber)

Series([], Name: MemberCouncilNumber, dtype: int64)
Series([], Name: MemberCouncilNumber, dtype: int64)
Series([], Name: MemberCouncilNumber, dtype: int64)
Series([], Name: MemberCouncilNumber, dtype: int64)
Series([], Name: MemberCouncilNumber, dtype: int64)
27079    307
30261    354
Name: MemberCouncilNumber, dtype: int64
Series([], Name: MemberCouncilNumber, dtype: int64)
32718    214
Name: MemberCouncilNumber, dtype: int64
Series([], Name: MemberCouncilNumber, dtype: int64)
Series([], Name: MemberCouncilNumber, dtype: int64)
Series([], Name: MemberCouncilNumber, dtype: int64)
27708    214
Name: MemberCouncilNumber, dtype: int64
Series([], Name: MemberCouncilNumber, dtype: int64)
Series([], Name: MemberCouncilNumber, dtype: int64)
Series([], Name: MemberCouncilNumber, dtype: int64)
Series([], Name: MemberCouncilNumber, dtype: int64)
44034    214
Name: MemberCouncilNumber, dtype: int64
49085    172
Name: MemberCouncilNumber, dtype: int64
45131    172
Name: MemberCouncilNumber, dtype: int64
Series([], Name: MemberCouncilNumber, dtype: int64)
Series([], Name: MemberCouncilNumber, dtype: int64)
Series([], Name: MemberCouncilNumber, dtype: int64)
Series([], Name: MemberCouncilNumber, dtype: int64)
Series([], Name: MemberCouncilNumber, dtype: int64)
Series([], Name: MemberCouncilNumber, dtype: int64)
Series([], Name: MemberCouncilNumber, dtype: int64)
65232    307
Name: MemberCouncilNumber, dtype: int64
Series([], Name: MemberCouncilNumber, dtype: int64)
Series([], Name: MemberCouncilNumber, dtype: int64)
Series([], Name: MemberCouncilNumber, dtype: int64)
Series([], Name: MemberCouncilNumber, dtype: int64)
Series([], Name: MemberCouncilNumber, dtype: int64)
83056    477
Name: MemberCouncilNumber, dtype: int64
Series([], Name: MemberCouncilNumber, dtype: int64)
Series([], Name: MemberCouncilNumber, dtype: int64)
74102    477
Name: MemberCouncilNumber, dtype: int64
Series([], Name: MemberCouncilNumber, dtype: int64)
Series([], Name: MemberCouncilNumber, dtype: int64)
87881     477
88174     525
88391     502
89126     305
89567     488
90782     466
93394     341
96064     512
96234     224
96593     172
98087     487
101739    801
Name: MemberCouncilNumber, dtype: int64
Series([], Name: MemberCouncilNumber, dtype: int64)